// Code generated by "stringer -type=BookType -linecomment"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdventureStories-1]
	_ = x[Classics-2]
	_ = x[Crime-3]
	_ = x[FairyTales-4]
	_ = x[Fantasy-5]
	_ = x[HistoricalFiction-6]
	_ = x[Horror-7]
	_ = x[HumourAndSatire-8]
}

const _BookType_name = "adventure-storiesclassicscrimefairy-talesfantasyhistorical-fictionhorrorhumour-and-satire"

var _BookType_index = [...]uint8{0, 17, 25, 30, 41, 48, 66, 72, 89}

func (i BookType) String() string {
	i -= 1
	if i < 0 || i >= BookType(len(_BookType_index)-1) {
		return "BookType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BookType_name[_BookType_index[i]:_BookType_index[i+1]]
}
